#!/usr/bin/python3

languages_iso = {
    "sa": "ara",
    "bd": "ben",
    "bg": "bul",
    "mm": "bur",
    "ct": "cat",
    "cn": "chi",
    "hk": "chi",
    "cz": "cze",
    "dk": "dan",
    "nl": "dut",
    "gb": "eng",
    "ph": "fil",
    "fi": "fin",
    "fr": "fre",
    "de": "ger",
    "gr": "gre",
    "hu": "hun",
    "id": "ind",
    "it": "ita",
    "jp": "jpn",
    "kr": "kor",
    "my": "may",
    "mn": "mon",
    "ir": "per",
    "pl": "pol",
    "br": "por",
    "pt": "por",
    "ro": "rum",
    "ru": "rus",
    "rs": "hrv",
    "es": "spa",
    "mx": "spa",
    "se": "swe",
    "th": "tha",
    "tr": "tur",
    "ua": "ukr",
    "vn": "vie",
    " ": "NA"
}

languages_names = {
    "sa": "Arabic",
    "bd": "Bengali",
    "bg": "Bulgarian",
    "mm": "Burmese",
    "ct": "Catalan",
    "cn": "Chinese (Simp)",
    "hk": "Chinese (Trad)",
    "cz": "Czech",
    "dk": "Danish",
    "nl": "Dutch",
    "gb": "English",
    "ph": "Filipino",
    "fi": "Finnish",
    "fr": "French",
    "de": "German",
    "gr": "Greek",
    "hu": "Hungarian",
    "id": "Indonesian",
    "it": "Italian",
    "jp": "Japanese",
    "kr": "Korean",
    "my": "Malay",
    "mn": "Mongolian",
    "ir": "Persian",
    "pl": "Polish",
    "br": "Portuguese (Br)",
    "pt": "Portuguese (Pt)",
    "ro": "Romanian",
    "ru": "Russian",
    "rs": "Serbo-Croatian",
    "es": "Spanish (Es)",
    "mx": "Spanish (LATAM)",
    "se": "Swedish",
    "th": "Thai",
    "tr": "Turkish",
    "ua": "Ukrainian",
    "vn": "Vietnamese",
    " ": "Other"
}